format = '${username:hostname}$directory$git_branch$git_state$python$line_break$time$character'


[username]
format = "[($user])($style)"

[directory]
# Do not truncate the path if in git repo
truncate_to_repo = false

repo_root_style = "bright-green"
style = "green"

[git_branch]
format = "[($symbol$branch)]($style)"
style = "yellow"

[git_state]

[time]
disabled = false
format = '[$time]($style) '
time_format = '%R'

[python]
format = '[(\($virtualenv\))]($style)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Disable the command duration prompt
[cmd_duration]
disabled = true
