format = '$username$hostname$directory$git_branch$git_state$python$rust$nix_shell$kubernetes$line_break$time$character'


[username]
format = "[($user)]($style)"

style_user = 'bold bright-green'
style_root = 'bold red'

[hostname]
format = "[@$hostname]($style) "
style = 'bold dimmed green'

[directory]
# Do not truncate the path if in git repo
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "..."

repo_root_style = "bright-blue"
style = "blue"

[git_branch]
format = "[]($style)[($symbol$branch)](fg:black bg:$style)[]($style) "
style = "cyan"

[git_state]
style = 'bold bright-blue'

[time]
disabled = false
format = '[$time]($style) '
time_format = '%R'
style = "blue"

[python]
format = '[]($style)[($virtualenv:)($version)](bold fg:black bg:$style)[]($style) '
style = 'bright-blue'

[rust]
format = '[]($style)[($version)](bold fg:black bg:$style)[]($style) '
style = 'bright-red'

[nix_shell]
format = '[]($style)[($name:$state)](bold fg:black bg:$style)[]($style) '
style = 'bright-green'

[character]
success_symbol = '[❯](bold cyan)'
error_symbol = '[❯](bold red)'

[kubernetes]
disabled = false
format = "[]($style)[($symbol$context)](fg:black bg:$style)[]($style) "
style = "blue"
symbol = "󰠳 "
detect_files = [ '.k8s' ]
detect_folders = [ 'charts' ]
