format = '$username$hostname$directory$git_branch${custom.git_status_simplified}${custom.git_status_simplified_closer}$git_state$python$rust$nix_shell${custom.kubernetes}$fill${custom.weather}$line_break${custom.live-clock-icon}$time$character'


[username]
format = "[($user)]($style)"

style_user = 'bold bright-green'
style_root = 'bold red'

[hostname]
format = "[@$hostname]($style) "
style = 'bold dimmed green'

[directory]
# Do not truncate the path if in git repo
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "..."

repo_root_style = "bright-blue"
style = "blue"

[fill]
symbol = " "

[git_branch]
format = "[]($style)[($symbol$branch)](fg:black bg:$style)[ ](fg:$style bg:$style)"
style = "cyan"

[git_state]
style = 'bold bright-blue'

[time]
disabled = false
format = '[$time]($style) '
time_format = '%R'
style = "blue"

[python]
format = '[]($style)[($virtualenv:)($version)](bold fg:black bg:$style)[]($style) '
style = 'bright-blue'

[rust]
format = '[]($style)[($version)](bold fg:black bg:$style)[]($style) '
style = 'bright-red'

[nix_shell]
format = '[]($style)[($symbol$name:$state)](bold fg:black bg:$style)[]($style) '
symbol = ' '
style = 'bright-green'

[character]
success_symbol = '[❯](bold cyan)'
error_symbol = '[❯](bold red)'

[kubernetes]
disabled = true
format = "[]($style)[($symbol$context)](fg:black bg:$style)[]($style) "
style = "blue"
symbol = "󰠳 "
detect_files = [ '.k8s' ]
detect_folders = [ 'charts' ]

[custom.kubernetes]
command = "kubectl config current-context"
when = '''
test -f .k8s ||
(git rev-parse --show-toplevel > /dev/null 2>&1 &&
 test -f "$(git rev-parse --show-toplevel)/.k8s")
'''
style = "blue"
symbol = "󰠳 "
format = "[]($style)[($symbol$output)](fg:black bg:$style)[]($style) "

[custom.git_status_simplified]
format = "[$symbol](fg:black bg:$style)"
when = 'test -n "$(git status --porcelain)"'
symbol = '●'
style = 'cyan'
require_repo = true
shell = [ 'bash' ]

[custom.git_status_simplified_closer]
format = "[]($style) "
when = true
style = 'cyan'
require_repo = true

[custom.live-clock-icon]
command = 'h="";echo  ${h:$(date +%H)%12:1}'
description = "Live updating clock icon, changes hourly"
when = true
style = "fg:bright-blue bg:black"
format = "[$output ]($style)"

[custom.weather]
description = "Weather info by wttr.in"
command = 'curl_cache wttr.in/Hamburg?format=3'
when = true
symbol = ''
style = "bright-black"
