name = "Paul DURANT"
downloads-dir = "~/Downloads"
signature = "Cordialement,\nPaul DURANT"
default-page-size = 50
watch-cmds = ["mbsync -a"]

[gmail]
default = true
email = "p.durant@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "p.durant@gmail.com"
imap-passwd-cmd = "pass show gmail"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "p.durant@gmail.com"
smtp-passwd-cmd = "pass show gmail"

[outlook]
default-page-size = 25
signature = """
Regards,
Paul DURANT
Sent from Outlook
"""

imap-host = "outlook.office365.com"
imap-port = 993
imap-login = "pdurant@outlook.com"
imap-passwd-cmd = "echo -n password"

smtp-host = "smtp.office365.com"
smtp-port = 587
smtp-starttls = true
smtp-login = "pdurant@outlook.com"
smtp-passwd-cmd = "echo password"

[posteo]
name = "Paul D."
downloads-dir = "~/Downloads/posteo"
email = "paul.durant@posteo.test"

imap-host = "posteo.de"
imap-port = 993
imap-login = "paul.durant@posteo.com"
imap-passwd-cmd = "security find-internet-password -gs posteo -w"

smtp-host = "posteo.de"
smtp-port = 465
smtp-login = "paul.durant@posteo.com"
smtp-passwd-cmd = "security find-internet-password -gs posteo -w"
