name = "Lasse Haffke"
downloads-dir = "~/mail_attachments"

[accounts.uni]
email = "lasse.haffke@studium.uni-hamburg.de"

backend = "imap"
imap.host = "exchange.uni-hamburg.de"
imap.port = 993
imap.login = 'uni-hamburg\BAO1136'
imap.passwd.cmd = " bw get password stine"

message.send.backend = "smtp"
smtp.host = "exchange.uni-hamburg.de"
smtp.port = 587
smtp.starttls = true
smtp.login = "BAO1136"
smtp.passwd.cmd = " bw get password stine"


[accounts.professional]
email = "lasse@haffke.me"
default = true

backend = "imap"
imap.host = "mail.privateemail.com"
imap.port = 993
imap.login = "lasse@haffke.me"
imap.passwd.cmd = " bw get password namecheap_mail"

message.send.backend = "smtp"
smtp.host = "mail.privateemail.com"
smtp.port = 465
smtp.login = "lasse@haffke.me"
smtp.passwd.cmd = " bw get password namecheap_mail"


[accounts.private]
email = "lahaffke@gmx.de"

backend = "imap"
imap.host = "imap.gmx.net"
imap.port = 993
imap.login = "lahaffke@gmx.de"
imap.passwd.cmd = " bw get password gmx_mail"

message.send.backend = "smtp"
smtp.host = "mail.gmx.net"
smtp.port = 465
smtp.login = "lahaffke@gmx.de"
smtp.passwd.cmd = " bw get password gmx_mail"
