require("lazy").setup {
	"wbthomason/packer.nvim",
	"neovim/nvim-lspconfig",
	{ "hrsh7th/nvim-cmp",
		branch = "main",
		dependencies = {
			{ "hrsh7th/cmp-nvim-lsp", branch = "main" },
			{ "hrsh7th/cmp-buffer", branch = "main" },
			{ "hrsh7th/cmp-path", branch = "main" },
			{ "hrsh7th/cmp-omni", branch = "main" },
			{ "hrsh7th/cmp-nvim-lsp-signature-help", branch = "main" },
			{ "saadparwaiz1/cmp_luasnip", dependencies = "L3MON4D3/LuaSnip" },
			{ "hrsh7th/cmp-cmdline", branch = "main" },
			{ "rcarriga/cmp-dap" },
		}
	},
	"junegunn/vim-easy-align",
	"tpope/vim-fugitive",
	"nvim-lualine/lualine.nvim",
	"lasse16/nvim-colorizer.lua",
	"numToStr/Comment.nvim",
	"tpope/vim-surround",
	"wellle/targets.vim",
	"rhysd/clever-f.vim",
	{ "L3MON4D3/LuaSnip", dependencies = "rafamadriz/friendly-snippets" },
	{ "nvim-treesitter/nvim-treesitter",
		dependencies = {
			"nvim-treesitter/nvim-treesitter-context",
			"nvim-treesitter/nvim-treesitter-textobjects"
		}
	},
	{ "mfussenegger/nvim-dap", dependencies = "rcarriga/nvim-dap-ui" },
	{ "simrat39/rust-tools.nvim",
		dependencies = { "neovim/nvim-lspconfig", "mfussenegger/nvim-dap", "nvim-lua/plenary.nvim" },
	},
	-- use({ "jose-elias-alvarez/null-ls.nvim", branch = "main", requires = "nvim-lua/plenary.nvim" })
	{ "ThePrimeagen/harpoon", dependencies = "nvim-lua/plenary.nvim" },
	"rcarriga/nvim-notify",
	{ "folke/trouble.nvim", branch = "main" },
	"stevearc/dressing.nvim",
	"windwp/nvim-autopairs",
	"folke/which-key.nvim",
	"ahmedkhalf/project.nvim",
	"folke/neodev.nvim",
	"mrjones2014/smart-splits.nvim",
	{ 'nvim-telescope/telescope.nvim', tag = '0.1.1', dependencies = { 'nvim-lua/plenary.nvim' } },
	"numToStr/Navigator.nvim",
	'lewis6991/gitsigns.nvim',
	'benfowler/telescope-luasnip.nvim',
}
