#!/usr/bin/env bash

# [Requirement] fzf

# Add git files from the list of modified files by git ls-files

for arg in "$@"; do
	case $arg in
		--modified | -m)
			git ls-files --modified "$(git rev-parse --show-toplevel)" | fzf --multi --preview='git diff --color=always {} '| xargs -r git-add || return
			;;
		*)
			command git-add
	esac
done
