#!  /bin/bash

toplevel_directory="$(git rev-parse --show-toplevel)"

for arg in "$@"; do
	if [[ "$arg" = "--repo" ]]; then
		cd "$toplevel_directory" || exit
	fi
done

files=$(git ls-files --directory --other --exclude-standard --exclude .gitignore "$toplevel_directory" | fzf  --multi --preview='cat') && echo $files >> .gitignore
