[bash]
[bash.files]
"bash/.bashrc.tmpl"= { target = "~/.bashrc", type="template"}
"bash/.inputrc"="~/.inputrc"
"bash/.profile.tmpl"={ target="~/.profile", type="template"}
"bash/.bash_history"="~/.bash_history"

[git]
[git.files]
"git/.gitconfig.tmpl"={target= "~/.gitconfig", type = "template"}

[git.variables]
"git.name"=""
"git.email"=""

[tmux]
[tmux.files]
"tmux/.tmux.conf"="~/.tmux.conf"

[tree-sitter]
[tree-sitter.files]
"tree-sitter/.tree-sitter/bin"="~/.tree-sitter/bin"
"tree-sitter/.tree-sitter/config.json.tmpl"={target= "~/.tree-sitter/config.json", type="template"}

[tree-sitter.variables]
"tree-sitter.parser-directory"=""

[vifm]
[vifm.files]
"vifm/.config/vifm/colors"="~/.config/vifm"
"vifm/.config/vifm/scripts"="~/.config/vifm"
"vifm/.config/vifm/vifmrc"="~/.config/vifm/vifmrc"

[vim]
[vim.files]
"vim/.vim"={target= "~/.vim", type="symbolic"}
"vim/.vimrc"= {target="~/.vimrc", type="symbolic"}
