# Possible packages

[bash]
depends = [ "environment" ]
[direnv]
[environment]
[fzf]
# Currently fzf is installed as a vim package
# So, to avoid duplication the binary installed via the package
# is referenced when using on CLI.
depends= [ "vim" ]
[git]
[tmux]
[tree-sitter]
[vifm]
# Uses vim as a previewer and opening tool
depends=[ "vim" ]
[vim]
[ssh]
depends = [ "bash" ]
[rust]

################################################################################

[bash.files]
"bash/.bashrc.tmpl"= { target = "~/.bashrc", type="template"}
"bash/.inputrc"="~/.inputrc"
"bash/.profile.tmpl"={ target="~/.profile", type="template"}
"bash/.bash_history"="~/.bash_history"

[environment.variables]
# Replace this by future dotter built-in variable (Maybe)
"environment.dotfile_folder"="~/dotfiles"
"environment.folder_shortcuts"=[]

[git.files]
"git/.gitconfig.tmpl"={target= "~/.gitconfig", type = "template"}

[git.variables]
"git.name"=""
"git.email"=""

[tmux.files]
"tmux/.tmux.conf"="~/.tmux.conf"

[tree-sitter.files]
"tree-sitter/.tree-sitter/bin"={target="~/.tree-sitter/bin",type="symbolic"}
"tree-sitter/.tree-sitter/config.json.tmpl"={target= "~/.tree-sitter/config.json", type="template"}

[tree-sitter.variables]
"tree-sitter.parser-directory"=""


[vifm.files]
"vifm/.config/vifm/colors"="~/.config/vifm"
"vifm/.config/vifm/scripts"="~/.config/vifm"
"vifm/.config/vifm/vifmrc"="~/.config/vifm/vifmrc"

[vim.files]
"vim/.vim"={target= "~/.vim", type="symbolic"}
"vim/.vimrc"= {target="~/.vimrc", type="symbolic"}

[ssh.files]
"bash/helpers/ssh_agent.sh.tmpl"="bash/helpers/ssh_agent.sh"

[ssh.variables]
"ssh.key-files"=[]


[rust.variables]
"rust.cargo_home"="~/.cargo"
"rust.rustup_home"="~/.rustup"
