[helpers]

[default]
depends = []

[default.files]
"README.md" = ""
bash = ""
colors = ""
"config_helper.sh" = ""
direnv = ""
"disable_all.sh" = ""
dotter = ""
git = ""
"local-data.toml" = ""
notes_rpi_install = ""
"setup_full.sh" = ""
tmux = ""
tree-sitter = ""
vifm = ""
vim = ""

[bash]
[bash.files]
"bash/.bashrc"="~/.bashrc"
"bash/.inputrc"="~/.inputrc"
"bash/.profile"="~/.profile"
"bash/.bash_history"="~/.bash_history"

[git]
[git.files]
"git/.gitconfig"="~/.gitconfig"

[git.variables]
"git.name"=""
"git.email"=""

[tmux]
[tmux.files]
"tmux/.tmux.conf"="~/.tmux.conf"

[tree-sitter]
[tree-sitter.files]
"tree-sitter/.tree-sitter"="~"

[vifm]
[vifm.files]
"vifm/.config/vifm/colors"="~/.config/vifm"
"vifm/.config/vifm/scripts"="~/.config/vifm"
"vifm/.config/vifm/vifmrc"="~/.config/vifm/vifmrc"

[vim]
[vim.files]
"vim/.vim"="~"
"vim/.vimrc"="~"
