# Possible packages

[alacritty]
[bash]
depends = ["environment"]
[direnv]
[environment]
[fzf]
[git]
[go]
[gpg]
[himalaya]
[khard]
[lf]
[nixos]
[nvim]
[tmux]
[tree-sitter]
[volta]
depends = ["environment"]
[ssh]
depends = ["bash"]
[starship]
[rust]
[zk]

################################################################################
[alacritty.files]
"alacritty/alacritty.yml" = { target = "~/.config/alacritty/alacritty.yml", type = "symbolic" }

[bash.files]
"bash/.bashrc.tmpl" = { target = "~/.bashrc", type = "template" }
"bash/.inputrc" = "~/.inputrc"
"bash/.profile.tmpl" = { target = "~/.profile", type = "template" }

[bash.variables]
"bash.browser" = "firefox"

[environment.variables]
# Replace this by future dotter built-in variable (Maybe)
"environment.dotfile_folder" = "$DOTFILES"

[git.files]
"git/.gitconfig.tmpl" = { target = "~/.gitconfig", type = "template" }
"git/.gitignore" = { target = "~/.gitignore", type = "symbolic" }

[git.variables]
"git.name" = ""
"git.email" = ""
"git.default_ssh_key" = ""
"git.special-dirs" = []

[gpg.variables]
"gpg.signingKey" = ""

[himalaya.variables]
"himalaya.name" = ""

[himalaya.files]
"himalaya/config.toml" = { target = "~/.config/himalaya/config.toml", type = "symbolic" }

[khard.files]
"khard/khard.conf" = { target = "~/.config/khard/khard.conf", type = "symbolic" }

[lf.files]
"lf/lfrc.tmpl" = { target = "~/.config/lf/lfrc", type = "template" }

[nixos.files]
"nixos/configuration.nix" = { target = "/etc/nixos/configuration.nix", type ="symbolic" }
"nixos/flake.nix" = { target = "/etc/nixos/flake.nix", type ="symbolic" }

[nvim.files]
"nvim/init.lua" = { target = "~/.config/nvim/init.lua", type = "symbolic" }
"nvim/lua" = { target = "~/.config/nvim/lua", type = "symbolic" }
"nvim/colors" = { target = "~/.config/nvim/colors", type = "symbolic" }
"nvim/plugin" = { target = "~/.config/nvim/plugin", type = "symbolic" }
"nvim/after" = { target = "~/.config/nvim/after", type = "symbolic" }
"nvim/spell" = { target = "~/.config/nvim/spell", type = "symbolic" }
"nvim/ftdetect" = { target = "~/.config/nvim/ftdetect", type = "symbolic" }

[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"

[ssh.files]
"bash/helpers/ssh_agent.sh.tmpl" = "bash/helpers/ssh_agent.sh"

[ssh.variables]
"ssh.key-files" = []

[starship.files]
"starship/config.toml.tmpl" = { target = "~/.config/starship/starship.toml", type = "template" }

[starship.variables]
"starship.weather-widget-home" = ""

[rust.variables]
"rust.cargo_home" = "~/.cargo"
"rust.rustup_home" = "~/.rustup"

[volta.variables]
"volta.home" = "~/.config/volta"

[zk.files]
"zk/config.toml" = { target = "~/.config/zk/config.toml", type = "symbolic" }
