# Possible packages

[bash]
depends = [ "environment" ]
[direnv]
[environment]
[fzf]
[git]
[himalaya]
[lf]
[nvim]
[tmux]
[tree-sitter]
[vim]
[volta]
depends=[ "environment" ]
[ssh]
depends = [ "bash" ]
[starship]
depends = [ "bash" ]
[rust]

################################################################################

[bash.files]
"bash/.bashrc.tmpl"= { target = "~/.bashrc", type="template"}
"bash/.inputrc"="~/.inputrc"
"bash/.profile.tmpl"={ target="~/.profile", type="template"}
"bash/.bash_history"="~/.bash_history"

[environment.variables]
# Replace this by future dotter built-in variable (Maybe)
"environment.dotfile_folder"="$DOTFILES"
"environment.bookmarks"=[]

[fzf.variables]
"fzf.home_directory"="$HOME/src/fzf"

[git.files]
"git/.gitconfig.tmpl"={target= "~/.gitconfig", type = "template"}

[git.variables]
"git.name"=""
"git.email"=""

[himalaya.variables]
"himalaya.name" = ""

[himalaya.files]
"himalaya/config.toml" ={target = "~/.config/himalaya/config.toml", type = "symbolic"}

[lf.files]
"lf/lfrc.tmpl"={target= "~/.config/lf/lfrc", type = "template"}

[nvim.files]
"nvim/init.lua"={target= "~/.config/nvim/init.lua", type = "symbolic"}
"nvim/lua"={target= "~/.config/nvim/lua", type = "symbolic"}
"nvim/autoload"={target= "~/.config/nvim/autoload", type = "symbolic"}
"nvim/colors"={target= "~/.config/nvim/colors", type = "symbolic"}
"nvim/plugin"={target= "~/.config/nvim/plugin", type = "symbolic"}
"nvim/after"={target= "~/.config/nvim/after", type = "symbolic"}

[tmux.files]
"tmux/.tmux.conf"="~/.tmux.conf"

[tree-sitter.files]
"tree-sitter/bin"={target="~/.tree-sitter/bin",type="symbolic"}
"tree-sitter/config.json.tmpl"={target= "~/.tree-sitter/config.json", type="template"}

[tree-sitter.variables]
"tree-sitter.parser-directory"=""

[vim.files]
"vim/.vimrc.tmpl"= {target="~/.vimrc", type="template"}
[vim.variables]
"vim.plugin_dir"="~/.vim/plugged"

[ssh.files]
"bash/helpers/ssh_agent.sh.tmpl"="bash/helpers/ssh_agent.sh"

[ssh.variables]
"ssh.key-files"=[]

[starship.files]
"starship/config.toml"={target = "~/.config/starship.toml", type="symbolic"}

[rust.variables]
"rust.cargo_home"="~/.cargo"
"rust.rustup_home"="~/.rustup"

[volta.variables]
"volta.home"="~/.config/volta"
