# ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# ls aliasies exa-style
alias ll='exa -aalF'
alias la='exa -a'
alias l='exa -F'

# himalaya 
alias mail='himalaya'

alias pwdf="readlink -f"
alias python="python3"
alias grip="grip -b --quiet"
alias path='echo $PATH | tr -s ":" "\n"'

# Shortening of common tools
alias tf=terraform
alias tg=terragrunt

alias g=git

alias k=kubectl
